TESTPROG tests_list START
TESTCASE tests_list:tst_create BEGIN
  tests_list:tst_create: getdns_list_create
  tests_list:tst_create: getdns_list_destroy(list)
  tests_list:tst_create: getdns_list_destroy(NULL)
  tests_list:tst_create: getdns_add_item(list) past block size
  tests_list:tst_create: getdns_list_get_length(list)
  tests_list:tst_create: list length = 12
  tests_list:tst_create: getdns_list_get_length()
  tests_list:tst_create: NUll, &i, retval = 304
  tests_list:tst_create: NUll, NULL, retval = 304
  tests_list:tst_create: list, NULL, retval = 304
TESTCASE tests_list:tst_create END
TESTCASE tests_list:tst_setget BEGIN
  tests_list:tst_setget: getdns_list_get_int() empty list
  tests_list:tst_setget: getdns_list_get_int(NULL, index, &ans_int),retval = 304
  tests_list:tst_setget: getdns_list_get_int(list, index, NULL),retval = 304
  tests_list:tst_setget: getdns_list_get_int(list, 0, &ans_int)
  tests_list:tst_setget: getdns_list_get_int,retval = 304
  tests_list:tst_setget: getdns_list_get_int(list, 1, &ans_int)
  tests_list:tst_setget: getdns_list_set_int,retval = 304
TESTCASE tests_list:tst_setget END
TESTPROG tests_list END
