TESTPROG tests_dict START
TESTCASE tests_dict:tst_create BEGIN
  tests_dict:tst_create: getdns_dict_create
  tests_dict:tst_create: getdns_dict_destroy(dict)
  tests_dict:tst_create: getdns_dict_destroy(NULL)
TESTCASE tests_dict:tst_create END
TESTCASE tests_dict:tst_bindatasetget BEGIN
  tests_dict:tst_bindatasetget: getdns_dict_get_bindata() empty dict
  tests_dict:tst_bindatasetget: line 61: getdns_dict_get_bindata(NULL, key, &ans_bdata),retval = 305
  tests_dict:tst_bindatasetget: line 65: getdns_dict_get_bindata(dict, key, NULL),retval = 305
  tests_dict:tst_bindatasetget: getdns_dict_get_bindata(dict, NULL, &ans_bindata)
  tests_dict:tst_bindatasetget: line 70: getdns_dict_get_bindata,retval = 305
  tests_dict:tst_bindatasetget: getdns_dict_get_bindata(dict, key, &ans_bdata)
  tests_dict:tst_bindatasetget: line 75: getdns_list_get_bindata,retval = 305
  tests_dict:tst_bindatasetget: getdns_dict_set_bindata(dict, key, bindata)
  tests_dict:tst_bindatasetget: line 93: getdns_dict_set_bindata,retval=0,key=foo
  tests_dict:tst_bindatasetget: getdns_dict_get_bindata(dict, key, &ans_bdata)
  tests_dict:tst_bindatasetget: line 98: getdns_dict_get_bindata,retval=0,key=foo,data=foobar
TESTCASE tests_dict:tst_bindatasetget END
TESTCASE tests_dict:tst_dictsetget BEGIN
  tests_dict:tst_dictsetget: getdns_dict_get_dict() empty dict
  tests_dict:tst_dictsetget: line 136: getdns_dict_get_dict(NULL, key, &ansdict),retval = 305
  tests_dict:tst_dictsetget: line 140: getdns_dict_get_dict(dict, key, NULL),retval = 305
  tests_dict:tst_dictsetget: getdns_dict_get_dict(dict, NULL, &ansdict)
  tests_dict:tst_dictsetget: line 145: getdns_dict_get_dict,retval = 305
  tests_dict:tst_dictsetget: getdns_dict_get_dict(dict, key, &ansdict)
  tests_dict:tst_dictsetget: line 150: getdns_list_get_dict,retval = 305
  tests_dict:tst_dictsetget: getdns_dict_set_dict(dict, key, newdict)
  tests_dict:tst_dictsetget: line 168: getdns_dict_set_dict,retval=0,key=foo
  tests_dict:tst_dictsetget: getdns_dict_get_dict(dict, key, &ansdict)
  tests_dict:tst_dictsetget: line 177: getdns_dict_get_dict,retval=0,key=foo,int1=42,int2=52
TESTCASE tests_dict:tst_dictsetget END
TESTCASE tests_dict:tst_intsetget BEGIN
  tests_dict:tst_intsetget: getdns_dict_get_int() empty dict
  tests_dict:tst_intsetget: line 375: getdns_dict_get_int(NULL, key, &ans_int),retval = 305
  tests_dict:tst_intsetget: line 379: getdns_dict_get_int(dict, key, NULL),retval = 305
  tests_dict:tst_intsetget: getdns_dict_get_int(dict, NULL, &ans_int)
  tests_dict:tst_intsetget: line 384: getdns_dict_get_int,retval = 305
  tests_dict:tst_intsetget: getdns_dict_get_int(dict, key, &ans_int)
  tests_dict:tst_intsetget: line 389: getdns_list_get_int,retval = 305
  tests_dict:tst_intsetget: getdns_dict_set_int(dict, key, newint)
  tests_dict:tst_intsetget: line 405: getdns_dict_set_int,retval=0,key=foo,int=42
  tests_dict:tst_intsetget: getdns_dict_get_int(dict, key, &ans_int)
  tests_dict:tst_intsetget: line 410: getdns_dict_get_int,retval=0,key=foo,int=42
  tests_dict:tst_intsetget: getdns_dict_set_int(dict, key, newint)
  tests_dict:tst_intsetget: line 417: getdns_dict_set_int,retval=0,key=bar,int=52
  tests_dict:tst_intsetget: getdns_dict_get_int(dict, key, &ans_int)
  tests_dict:tst_intsetget: line 422: getdns_dict_get_int,retval=0,key=bar,int=52
  tests_dict:tst_intsetget: getdns_dict_get_data_type(dict, key, &dtype)
  tests_dict:tst_intsetget: line 427: getdns_dict_get_data_type,retval=0,key=bar,dtype=2
TESTCASE tests_dict:tst_intsetget END
TESTCASE tests_dict:tst_listsetget BEGIN
  tests_dict:tst_listsetget: getdns_dict_get_list() empty dict
  tests_dict:tst_listsetget: line 297: getdns_dict_get_list(NULL, key, &anslist),retval = 305
  tests_dict:tst_listsetget: line 301: getdns_dict_get_list(dict, key, NULL),retval = 305
  tests_dict:tst_listsetget: getdns_dict_get_list(dict, NULL, &anslist)
  tests_dict:tst_listsetget: line 306: getdns_dict_get_list,retval = 305
  tests_dict:tst_listsetget: getdns_dict_get_list(dict, key, &anslist)
  tests_dict:tst_listsetget: line 311: getdns_list_get_list,retval = 305
  tests_dict:tst_listsetget: getdns_dict_set_list(dict, key, newlist)
  tests_dict:tst_listsetget: line 331: getdns_dict_set_list,retval=0,key=foo
  tests_dict:tst_listsetget: getdns_dict_get_list(dict, key, &anslist)
  tests_dict:tst_listsetget: line 340: getdns_dict_get_list,retval=0,key=foo,int1=42,int2=52
TESTCASE tests_dict:tst_listsetget END
TESTCASE tests_dict:tst_getnames BEGIN
  tests_dict:tst_getnames: getdns_dict_get_names(NULL, &list)
  tests_dict:tst_getnames: getdns_dict_get_names(dict, NULL)
  tests_dict:tst_getnames: getdns_dict_get_names(dict, &list), empty dictionary
    list item 0: t_int, value=3
    list item 1: t_int, value=1
    list item 2: t_int, value=0
    list item 3: t_int, value=2
TESTCASE tests_dict:tst_getnames END
TESTCASE tests_dict:tst_copy BEGIN
  tests_dict:tst_copy: empty list cases
  tests_dict:tst_copy: dict1 populate
key="bar", type="int", value="52"
key="foo", type="int", value="42"
key="quz", type="int", value="62"
  tests_dict:tst_copy: getdns_dict_copy(dict1, &dict2)
key="bar", type="int", value="52"
key="foo", type="int", value="42"
key="quz", type="int", value="62"
TESTCASE tests_dict:tst_copy END
TESTPROG tests_dict END
